name: Build and Deploy Docker Bot

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/natal-carts-bot:latest

      - name: Deploy to Vultr Instance via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VULTR_HOST }}
          username: ${{ secrets.VULTR_USER }}
          key: ${{ secrets.VULTR_SSH_KEY }}
          port: ${{ secrets.VULTR_SSH_PORT || '22' }}
          script: |
            # Pull the latest image from Docker Hub
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/natal-carts-bot:latest
            # Stop and remove the existing container if it exists
            docker stop natal-carts-bot || true
            docker rm natal-carts-bot || true
            # Run the new container in detached mode
            docker run -d --restart unless-stopped --name natal-carts-bot \
                      -e TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} \
                      ${{ secrets.DOCKERHUB_USERNAME }}/natal-carts-bot:latest